output_folder: "../logs"
dataset:
  name: "COCO"
  img_folder: "../data/coco"
  json_folder: "../data/coco/annotations"
  train: "train2017"
  test: "val2017"

# other parameters can be specified in this yaml file
# e.g. the following lines will reset the number of training epochs to 8
opt:
 epochs: 4
 type: "SGD"
 learning_rate: 0.0005

model:
  num_classes: 80

# see config.py for more details
